services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-global
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    networks:
      - ap2-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq123"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ap2-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    restart: always
    environment:
      PORT: "8081"
      GRPC_HOST: "0.0.0.0"
      GRPC_PORT: "9091"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "123456"
      DB_NAME: "payment_db"
      DB_SSLMODE: "disable"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: "rabbitmq"
      RABBITMQ_PASSWORD: "rabbitmq123"
    ports:
      - "8081:8081"
      - "9091:9091"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ap2-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    restart: always
    environment:
      PORT: "8080"
      GRPC_HOST: "0.0.0.0"
      ORDER_GRPC_PORT: "9090"
      PAYMENT_GRPC_ADDRESS: "payment-service:9091"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "123456"
      DB_NAME: "order_db"
      DB_SSLMODE: "disable"
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy
      payment-service:
        condition: service_started
    networks:
      - ap2-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    restart: always
    environment:
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "123456"
      DB_NAME: "notification_db"
      DB_SSLMODE: "disable"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: "rabbitmq"
      RABBITMQ_PASSWORD: "rabbitmq123"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ap2-network

networks:
  ap2-network:
    driver: bridge

volumes:
  postgres-data:
