services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-global
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /home/nurashi/storage/postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
